const productsData = [
  // --- CANNED FISH ---
  {
    id: 1,
    category: "canned-fish",
    name: "White Tuna in Olive Oil",
    image: "/img/canned-tunaFucsia.jpeg",
    story: "White Tuna (Bonito del Norte) caught in the Cantabrian Sea and traditionally prepared. Each piece is carefully selected and slow-cooked at a low temperature to preserve its natural texture and flavor, then packed in olive oil to enhance its delicate taste profile..",
    ingredients: "Color: Pinkish white, Aroma: Mild, cooked fish with olive oil, Flavor: Delicate, typical of White Tuna, Texture: Firm and flaky",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },
  {
    id: 2,
    category: "canned-fish",
    name: "Natural Clams",
    image: "/img/canned-tunaCeleste.jpeg",
    story: "Clams in Their Natural Juices with Purified Seawater. The Portuguese and Galician coasts are sisters of the same sea. These clams, sourced from the Ría de Aveiro, are purified in seawater for hours to remove every trace of sand. They are then gently cooked, carefully shucked, meticulously sorted, and hand-packed.",
    ingredients: "Authentic sea flavor, delicate and pure, with the natural taste of freshly harvested clams. Tender texture on the palate",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },
  {
    id: 3,
    category: "canned-fish",
    name: "Garlic Octopus",
    image: "/img/canned-tunaPurple.jpeg",
    story: "Octopus (Eledone cirrhosa) with a mild flavor, ideal for creative culinary preparations.",
    ingredients: "Appearance: Pinkish color with firm texture, Aroma: Subtle garlic scent, Flavor: Mild, delicate taste with hints of garlic, Texture: Firm yet tender",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },
  {
    id: 4,
    category: "canned-fish",
    name: "Spicy Sardines in Olive Oil",
    image: "/img/canned-tunaRojo.jpeg",
    story: "Pilchard sardines in olive oil with piri-piri, perfect for lovers of spicy flavors. We work with the species Sardina pilchardus, widely regarded as the finest and most highly prized for its exceptional quality.",
    ingredients: "Appearance: Firm sardines with a light golden hue from the olive oil, Aroma: Fresh marine scent with a hint of spice, Flavor: Spicy touch that enhances the natural taste of the sardines, Texture: Tender and juicy",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },
  {
    id: 5,
    category: "canned-fish",
    name: "Tuna Bell in Olive Oil",
    image: "/img/canned-tunaRosa.jpeg",
    story: "Within the finest of all species, Thunnus alalunga, we select only the ventresca — its most prized, and flavorful cut — for this preserve. This triangular piece, located on the lower part of the fish, is distinguished by its delicate structure and exceptional richness.",
    ingredients: "Smooth and juicy texture. Intense tuna flavor with a delicate touch of olive oil.",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },
  {
    id: 6,
    category: "canned-fish",
    name: "Sardines in Olive Oil",
    image: "/img/canned-tunaVerde.jpeg",
    story: "Sardines in Mediterranean Olive Oil. We work exclusively with the species Sardina pilchardus, regarded as the finest and most highly prized for its superior quality. Our sardines are caught in the Mediterranean Sea by small-scale coastal fleets, ensuring the responsible and sustainable use of marine resources.",
    ingredients: "Appearance: Large, meaty sardines, Aroma: Intense olive oil scent, Flavor: Rich and savory, with a pronounced olive oil taste, Texture: Tender and succulent",
    allergens: "Contains fish. May contain traces of crustaceans.",
    available: true,
  },

  // --- OLIVE OIL ---
  {
    id: 7,
    category: "olive-oil",
    name: "Extra Virgin Olive Oil",
    image: "/img/ProductOlive.jpg",
    story: "Cold-pressed extra virgin olive oil from hand-picked Arbequina olives. Smooth and fruity finish.",
    ingredients: "100% extra virgin olive oil (Arbequina).",
    allergens: "None.",
    available: true,
  },
  {
    id: 8,
    category: "olive-oil",
    name: "Olive Oil with Cayene",
    image: "/img/ProductOliveCayene.jpg",
    story: "Extra virgin olive oil infused with cayenne pepper. Adds a warm, spicy kick to any dish.",
    ingredients: "Extra virgin olive oil, cayenne pepper.",
    allergens: "None.",
    available: true,
  },
  {
    id: 9,
    category: "olive-oil",
    name: "Olive Oil with Lemon",
    image: "/img/ProductOliveLemon.jpg",
    story: "Bright and citrusy olive oil infused with fresh lemon zest. Perfect for salads and seafood.",
    ingredients: "Extra virgin olive oil, lemon zest.",
    allergens: "None.",
    available: true,
  },
  {
    id: 10,
    category: "olive-oil",
    name: "Olive Oil with Rosemary",
    image: "/img/ProductOliveRosemari.jpg",
    story: "Aromatic olive oil infused with Mediterranean rosemary. Ideal for grilled vegetables and meats.",
    ingredients: "Extra virgin olive oil, rosemary.",
    allergens: "None.",
    available: true,
  },
  {
    id: 11,
    category: "olive-oil",
    name: "Olive Oil with Truffle",
    image: "/img/ProductOliveTrufa.jpg",
    story: "Luxurious extra virgin olive oil with black truffle. The ultimate finishing oil for gourmet dishes.",
    ingredients: "Extra virgin olive oil, black truffle extract.",
    allergens: "None.",
    available: true,
  },
];

export default productsData;
